### PR TITLE
feat: use onPreResponse as extension point

### PR DESCRIPTION
**Pull request by nimerritt**
This plugin should run last, even after other onPreResponse handlers
such as custom error wrappers. This requires us to use the onPreResponse
handler.

In addition, we now return a 501 for non-specified routes rather than
404.

### CODE REVIEW

**Comment by jishi** [comment]
Why the 501? Seems more confusing than actually solving anything

**Comment by nimerritt** [comment]
What would you prefer over the 501?

**Comment by nimerritt** [comment]
@jishi Or were you referring to returning the 501 instead of 404 when a route is not defined?

**Comment by jishi** [comment]
Yeah, why we change the 404 which is a very well established standard :)

**Comment by jishi** [comment]
If we were to implement the 501 for routes that exists, but are called with the wrong verb, that would be an improvement though.

**Comment by nimerritt** [comment]
My argument is that we might actually want a 404 but forget to define the API spec and the tests passes anyways. This also makes it easier to debug in my opinion, as the reason is very clearly stated in the error message.

I can change it if we find it confusing in the future.

**Pull request merged**
